version: 2

updates:
  # Maintain dependencies for python packages
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    # Disable version updates for python dependencies
    # This option has no impact on security updates, which have a separate, internal limit of ten open pull requests.
    open-pull-requests-limit: 0
    reviewers:
      - "Mudaafi" # Ahmad
      - "esezen" # Enes
