language: python

addons:
  apt_packages:
    - pandoc

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "nightly"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install -r requirements-py2.txt; fi
  - pip install -r requirements.txt

script:
  - pandoc --from=markdown --to=rst --output=README.rst README.md
  - pip install -e .
  - pytest