language: python
addons:
  apt_packages:
  - pandoc
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
#- 3.7-dev
#- nightly
install:
- if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install -r requirements-py2.txt; fi
- pip install -r requirements.txt
script:
- pandoc --from=markdown --to=rst --output=README.rst README.md
- pip install -e .
- pytest
deploy:
  - provider: pypi
    skip_cleanup: true
    distributions: sdist
    user: "Constructor"
    password:
      secure: ULDlGLHMGbuWOPchVcbJx1lDHHKIm1X62TyMqlbu0TFVKK6n+cbmGxLR4k/oVzcGEc/tTftOmM0jThkE4+krbekMovGjvwmxzyXsGvlXsCpfOvE7anjsmA2+bKVAyjtoXxyz2uarJaiqK9t6kl3agJ4O8gi4LfwdS5uZnFmE8CjjsiTxhRPhQTl14jhI57L0pOsSTSemwjy0x0zJ83WwMLOViA9FOn9N8do5S2HPNFH4gqZV8WAU4A4L2XA+OmpWKHoMdEbxAhnM6ObaHUBy1xMBpD/Cq7HM45xh+iWvXQ3OdWywU8X2zGFnfi8KsOZO5mNX2nFKgGMsdZS/p/2vLY2lSo/qSokDDqdn9FP5sItSa7BHKcMPQGK9vfEMkeYfpoRRFTa/ZXOSvE/hdHIT/qqNP4d/fzAwC6p42nDREwqvBI1LcY+rMi4KCAvH3Z+d4vV6eWQ/AUo/fIgwT0jbbG+fXBqe3zn4qdwC3hqWUcNpXbarT39UduZADgbO3vGuJfLYS8k0jWU45609/CkSC5RV0LrHUGY2atTcNBhv0hAOUTCouVtaiCNTNAr79YrQwTv9aFDVB1VdZkjRFgoK3A2OgB0Jh4FkprDbycMTGu4UkYGspbK4a943TK/OpipAPeSji7orZzvFgy0tEMWhBtxFwWurt3PaUdXcc/ctDVo=
    on:
      branch: master
      condition: $TRAVIS_PYTHON_VERSION = "3.6"
      tags: true
