name: 'Check for Dependabot alerts & send them to Slack'

on:
  schedule:
    - cron: '30 16 * * *' # every day at 9:30 am PST
  workflow_dispatch: # to have the option to run this ad-hoc

jobs:
  main:
    uses: Constructor-io/customer-integrations-github-workflows/blob/main/workflows/dependabot-alerts-to-slack.yml@main
